export const CREATE_RECIPE = 'CREATE_RECIPE';

export const SET_BASIC_FIELD_VALUES = 'SET_BASIC_FIELD_VALUES';
export const SET_LOCAL_IMAGE = 'SET_LOCAL_IMAGE';
export const REMOVE_LOCAL_IMAGE = 'REMOVE_LOCAL_IMAGE';
export const SET_IMGBB_IMAGE = 'SET_IMGBB_IMAGE';
export const REMOVE_IMGBB_IMAGE = 'REMOVE_IMGBB_IMAGE';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';

export const SET_CURRENT_STEP_VALUE = 'SET_CURRENT_STEP_VALUE';
export const ADD_RECIPE_STEP = 'ADD_RECIPE_STEP';
export const REMOVE_RECIPE_STEP = 'REMOVE_RECIPE_STEP';
export const CLEAR_RECIPE_STEPS = 'CLEAR_RECIPE_STEPS';
export const SET_RECIPE_STEPS = 'SET_RECIPE_STEPS';
export const SET_STEP_TO_EDIT = 'SET_STEP_TO_EDIT';
export const SET_EDIT_INPUT_VALUE = 'SET_EDIT_INPUT_VALUE';
export const SAVE_STEP_CHANGES = 'SAVE_STEP_CHANGES';
export const CANCEL_STEP_CHANGES = 'CANCEL_STEP_CHANGES';

export const POPULATE_FROM_LOCALSTORAGE = 'POPULATE_FROM_LOCALSTORAGE'
export const RESET_ALL_FIELDS = 'RESET_ALL_FIELDS';