export const CREATE_RECIPE = 'CREATE_RECIPE';
export const SET_RECIPE_FIELD_VALUES = 'SET_RECIPE_FIELD_VALUES';
export const SET_RECIPE_INGREDIENTS = 'SET_RECIPE_INGREDIENTS';
export const SET_RECIPE_STEPS = 'SET_RECIPE_STEPS';