// ##################### CREATE/EDIT RECIPE ###################
export const CREATE_RECIPE = 'CREATE_RECIPE';

export const SET_BASIC_FIELD_VALUES = 'SET_BASIC_FIELD_VALUES';
export const SET_LOCAL_IMAGE = 'SET_LOCAL_IMAGE';
export const REMOVE_LOCAL_IMAGE = 'REMOVE_LOCAL_IMAGE';
export const SET_IMGBB_IMAGE = 'SET_IMGBB_IMAGE';
export const REMOVE_IMGBB_IMAGE = 'REMOVE_IMGBB_IMAGE';

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const CLEAR_INGREDIENTS = 'CLEAR_INGREDIENTS';

export const SET_CURRENT_STEP_VALUE = 'SET_CURRENT_STEP_VALUE';
export const ADD_RECIPE_STEP = 'ADD_RECIPE_STEP';
export const REMOVE_RECIPE_STEP = 'REMOVE_RECIPE_STEP';
export const SET_RECIPE_STEPS = 'SET_RECIPE_STEPS';
export const SET_STEP_TO_EDIT = 'SET_STEP_TO_EDIT';
export const SET_EDIT_INPUT_VALUE = 'SET_EDIT_INPUT_VALUE';
export const SAVE_STEP_CHANGES = 'SAVE_STEP_CHANGES';
export const CANCEL_STEP_CHANGES = 'CANCEL_STEP_CHANGES';

export const POPULATE_FROM_LOCALSTORAGE = 'POPULATE_FROM_LOCALSTORAGE'
export const RESET_ALL_FIELDS = 'RESET_ALL_FIELDS';
export const SET_ACTION_SUCCESSFUL_TO_FALSE = 'SET_ACTION_SUCCESSFUL_TO_FALSE';
export const SET_IMAGE_LOADING = 'SET_IMAGE_LOADING';

// ##################### MY RECIPES ###################
export const FETCH_USER_RECIPES = 'FETCH_USER_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const REMOVE_RECIPE_BY_ID = 'REMOVE_RECIPE_BY_ID';
export const EDIT_RECIPE_BY_ID = 'EDIT_RECIPE_BY_ID';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';