export const OPEN_MOBILE_MENU = 'OPEN_MOBILE_MENU';
export const CLOSE_MOBILE_MENU = 'CLOSE_MOBILE_MENU';
export const SET_BLURRED_BACKGROUND = 'SET_BLURRED_BACKGROUND';
export const SET_CLEAR_BACKGROUND = 'SET_CLEAR_BACKGROUND';
export const SET_TAB_TITLE = 'SET_TAB_TITLE';
export const SET_INFINITY_LIST_SETTINGS = 'SET_INFINITY_LIST_SETTINGS';