export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_SINGLE_RECIPE = 'GET_SINGLE_RECIPE';
export const GET_LATEST_RECIPES = 'GET_LATEST_RECIPES';
export const GET_RANDOM_SINGLE_RECIPE = 'GET_RANDOM_RECIPE';
export const GET_RANDOM_MULTIPLE_RECIPES = 'GET_RANDOM_MULTIPLE_RECIPES';
export const GET_RECIPES_BY_CATEGORY = 'GET_RECIPES_BY_CATEGORY';
export const GET_RECIPES_BY_INGREDIENT = 'GET_RECIPES_BY_INGREDIENT';
export const CLEAR_SINGLE_RECIPE = 'CLEAR_SINGLE_RECIPE';

export const SET_LOADING = 'SET_LOADING';